from rest_framework_simplejwt.views import TokenObtainPairView
from myapp.serializers.TokenSerializer import CustomTokenObtainPairSerializer

class CustomTokenObtainPairView(TokenObtainPairView):
    serializer_class = CustomTokenObtainPairSerializer